version: '2'
services:
    shareitv2-app:
        image: shareitv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shareitv2-postgresql:5432/shareItV2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shareitv2-postgresql:
        extends:
            file: postgresql.yml
            service: shareitv2-postgresql
